- name: Temp override for "hostname_fqdn"
  set_fact:
    hostname_fqdn  : "{{ inventory_hostname }}"
  when: hostname_fqdn is not defined

  # provisioned machine might have incorrect hostname if thats the case override facts to new name
- name: Temp override facts "ansible_fqdn"
  set_fact:
    ansible_fqdn : "{{ inventory_hostname }}"
  when: ansible_fqdn != inventory_hostname

- name: Set hostname short variable
  set_fact:
    hostname_short : "{{ lookup('template', '../templates/shortname.j2') }}"
  when: hostname_short is not defined

- name: Set machine hostname
  hostname:
    name: "{{ hostname_short }}"

- name: Temp override facts "hostname_short"
  set_fact:
    ansible_hostname  : "{{ hostname_short }}"
  when: ansible_hostname != hostname_short

- name: Ensure hostname is in /etc/hostname
  copy:
    content: "{{hostname_short}}{{'\n'}}"
    dest: /etc/hostname
    owner: root
    group: root
    mode: 0644

- name: Ensure hostname entries in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: "{{item.regexp}}"
    line: "{{item.line}}"
    state: present
  with_items: hostname_hosts_file
